components:
  labelExample:
    type: label
    enable: true
    x: "%w%-80*%w%/3001"
    y: "100"
    z: 50
    texts:
      - "test"
      - "test2"
  textureExample:
    type: texture
    enable: true
    path: "https://img0.baidu.com/it/u=3552184703,3895439571&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=500"
    x: "%w%-80*%w%/3001"
    y: "100"
    z: 50
    width: "59*%w%/300"
    height: "20*%w%/300"
  buttonExample:
    type: button
    enable: true
    defaultPath: "https://img1.baidu.com/it/u=3684449540,1854084134&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=500"
    pressedPath: "https://img1.baidu.com/it/u=3684449540,1854084134&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=500"
    hoverPath: "https://img1.baidu.com/it/u=3684449540,1854084134&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=500"
    x: "0"
    y: "0"
    z: 50
    width: 59
    height: 20
    actions:
      click: |
        map.consoleCommand("say "+map.getPlayer().getName()+" click");