version: 1.0
message:
  prefix: "&7AoitoriMap &f>> "

enableValidation: true
kickValidationTimeout: false
kickValidationTimeoutTime: 5000
resourcesKey: l8jo/RpfacKpfXIHQM1mCw==
autoReloadConfig: true
sendDataDelay: 2000
permanentGUI:
  - default